# -*- mode: ruby -*-
# vi: set ft=ruby :

# Set hostnames and ips of the machines
nodes = [
	{ :hostname => 'appserver', :ip => '192.168.0.1' },
	{ :hostname => 'dbserver', :ip => '192.168.0.2' }
]

Vagrant.configure("2") do |config|

  # Configure VirtualBox as the default provider, by running only "vagrant up" it automatically uses it
  config.vm.provider "virtualbox"
  config.vm.box = "bento/ubuntu-18.04"
    
  # Configure DigitalOcean as an optional provider, it runs when launching "vagrant up --provider=digital_ocean" from powershell
  config.vm.provider :digital_ocean do |provider, override|
	override.ssh.private_key_path = '~/.ssh/id_rsa'
	override.vm.box = 'digital_ocean'
	override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
	override.nfs.functional = false
	override.vm.allowed_synced_folder_types = :rsync
 
	provider.token = ENV['TOKEN'] #Use env varibale for the token
	provider.image = 'ubuntu-18-04-x64'
	provider.region = 'nyc1'
	provider.size = 's-1vcpu-1gb'
	provider.setup = false
  end

  # Configure appserver and database machines
  nodes.each do |node|
	config.vm.define node[:hostname] do |nodeconfig|
		nodeconfig.vm.hostname = node[:hostname]
		nodeconfig.vm.network :private_network, ip: node[:ip]
	end
  end

  #Install puppet on the machines for provisioning with it
  config.puppet_install.puppet_version = :latest
  #Configure puppet provisioning
  config.vm.provision :puppet do |puppet|
	puppet.environment_path = "environments"
	puppet.environment = "puppet"
	puppet.module_path = "environments/puppet/modules"
  end

end
