# -*- mode: ruby -*-
# vi: set ft=ruby :

# Setup our 2 main server nodes parameters
nodes = [
	{ :hostname => 'appserver', :ip => '192.168.0.1' },
	{ :hostname => 'dbserver', :ip => '192.168.0.2' }
]

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"

  # Configure our box to utilize puppet for provisioning
  config.vm.provision "shell", inline: <<-SHELL
	wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
	dpkg -i puppet5-release-$(lsb_release -cs).deb
	apt-get -qq update
	apt-get install -y puppet-agent
  SHELL

  #Configure guest machines
  nodes.each do |node|
	config.vm.define node[:hostname] do |nodeconfig|
		nodeconfig.vm.hostname = node[:hostname]
		nodeconfig.vm.network :private_network, ip: node[:ip]
	end
  end

  # Configure web server
  config.vm.define "web" do |web|
	web.vm.hostname = "web"
	web.vm.network "forwarded_port", guest: 80, host: 8080
	web.vm.network :private_network, ip: '192.168.0.3'
  end

  # Configure 3 test machines
  (0..2).each do |i|
	config.vm.define "tst#{i}" do |tst|
		tst.vm.hostname = "tst#{i}"
		tst.vm.network :private_network, ip: '192.168.0.4'
	end
  end

  # Configure puppet provisioning
  config.vm.provision :puppet do |puppet|
	puppet.environment_path = "environments"
	puppet.environment = "puppet"
	puppet.manifests_path = "environments/puppet/manifests"
	puppet.manifest_file = "site.pp"
	puppet.module_path = "environments/puppet/modules"
  end
  
end
